import type { TDocumentDefinitions } from "pdfmake/interfaces";
import { RISK_CATEGORY_LABELS, scoreColor } from "@/lib/constants/risks";
import { categoryBreakdown, scoreWithActions, type ScanSession } from "@/lib/scan/scanSession";

/**
 * Builds the PDFMake document for an audit.
 *
 * `redacted` produces the employer-facing variant (Could-Have in the PRD):
 * overall score + category counts only, never the post text.
 */
export function buildReportDoc(
  session: ScanSession,
  userName: string,
  redacted: boolean
): TDocumentDefinitions {
  const score = scoreWithActions(session.items, session.score);
  const breakdown = categoryBreakdown(session.items);
  const high = session.items.filter((i) => i.risk_level === "high").length;
  const medium = session.items.filter((i) => i.risk_level === "medium").length;
  const date = new Date(session.createdAt).toLocaleDateString();

  const flaggedRows = breakdown.map((row) => [
    RISK_CATEGORY_LABELS[row.category],
    String(row.count),
    String(row.high),
    String(row.medium)
  ]);

  const itemRows = session.items
    .filter((i) => i.risk_level !== "safe")
    .slice(0, 60)
    .map((i) => [
      i.risk_level.toUpperCase(),
      RISK_CATEGORY_LABELS[i.risk_category],
      i.date ? new Date(i.date).toLocaleDateString() : "-",
      { text: i.text, width: 260 }
    ]);

  const content: Record<string, unknown>[] = [
    { text: "ClearRecord AI — Digital Hygiene Report", style: "title" },
    { text: redacted ? "Employer summary (redacted)" : "Full audit report", style: "subtitle" },
    {
      text: [
        { text: "Candidate: ", bold: true },
        userName,
        { text: "   |   Generated: ", bold: true },
        date,
        { text: "   |   Archive: ", bold: true },
        session.fileName
      ],
      margin: [0, 0, 0, 16]
    },
    {
      columns: [
        { text: [{ text: String(score), fontSize: 40, bold: true, color: scoreColor(score) }, { text: " / 100", fontSize: 14 }] },
        { text: [{ text: String(session.totalScanned), bold: true }, { text: " items scanned" }] },
        { text: [{ text: String(high), bold: true, color: "#FF4444" }, { text: " high risk" }] },
        { text: [{ text: String(medium), bold: true, color: "#FFC107" }, { text: " medium risk" }] }
      ],
      margin: [0, 0, 0, 20]
    },
    { text: "Risk category breakdown", style: "h2" },
    {
      table: {
        headerRows: 1,
        widths: ["*", 60, 60, 70],
        body: [["Category", "Total", "High", "Medium"], ...flaggedRows]
      },
      layout: "lightHorizontalLines",
      margin: [0, 0, 0, 20]
    }
  ];

  if (!redacted) {
    content.push(
      { text: "Flagged items", style: "h2" },
      {
        text:
          "These posts are the ones most likely to be surfaced during employer screening. " +
          "Delete or edit them on the original platform, then re-run the audit.",
        margin: [0, 0, 0, 8]
      },
      {
        table: {
          headerRows: 1,
          widths: [60, 130, 70, "*"],
          body: [["Level", "Category", "Date", "Content"], ...itemRows]
        },
        layout: "lightHorizontalLines",
        fontSize: 9
      }
    );
  }

  content.push({
    text:
      "Generated by ClearRecord AI. Scores are an automated estimate based on public content " +
      "screening heuristics and AI classification, not a guarantee of any screening outcome.",
    fontSize: 8,
    italics: true,
    margin: [0, 20, 0, 0]
  });

  return {
    content,
    styles: {
      title: { fontSize: 20, bold: true, color: "#1DB954" },
      subtitle: { fontSize: 12, color: "#666666", margin: [0, 4, 0, 10] },
      h2: { fontSize: 13, bold: true, margin: [0, 8, 0, 6] }
    },
    defaultStyle: { fontSize: 10 }
  };
}
